version: "3.8"

services:

  web:
    image: nginx
    volumes:
    - ./client:/usr/share/nginx/html
    ports:
    - "80:80"
    environment:
    - NGINX_HOST=node
    - NGINX_PORT=3000
  db:
    image: mysql:latest # use latest version of mysql
    container_name: db # add a name for the container
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment: # add default values, see docs for more info.
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - '3306:3306'
    depends_on:
      - "web"
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
     - "8082:80"
    environment:
      MYSQL_ROOT_PASSWORD: mypassword #(Required) set the password for the root superuser account.
      PMA_HOST: db   # define the address/hostname of the mysql server eg mysql container name.
      PMA_USER: root # this is the root user to login on startup
      PMA_PASSWORD: mypassword # use the root password to login on startup.

  node:
    image: "node:latest"
    container_name: "node"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./server:/home/node/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - "db"
    command: sh -c "npm install express && npm install socket.io && npm install mysql && npm start"
